version: '3'

services:
  nginx:
      image: nginx
      ports:
          - 8080:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - php:/var/www/html
  php:
      build:
          context: .
      expose:
          - 9000
      volumes:
          - .:/var/www/html
  mysql:
      image: mariadb
      expose:
          - 3306
      ports:
          - 3306:3306
      volumes:
          - /var/lib/mysql
          - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: movies
          MYSQL_USER: movies
          MYSQL_PASSWORD: movies

networks:
  webnet:

volumes:
  database_data:
  php:
