version: '3'

volumes:
    php:

services:
    nginx:
        image: nginx:stable
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - php:/var/www/html

    php:
        build:
            context: .
        expose:
            - 9000
        volumes:
            - php:/var/www/html
